version: '3'
services:
  drpy2:
    image: drpy2
    build:
      context: .
      dockerfile: dockerfile
    container_name: drpy2
    ports:
      - "9001:9001"
      - "5705:5705"
    environment:
      - TZ=Asia/Shanghai
    restart: always